### ISSUE TITLE
Add wrapper functions to CollisionDetection for GridAreas

### ISSUE THREAD

**Issue by SamKn1ght** [y111studios/unisim#18]
This issue is designed to decrease the friction between the GameState object and the CollisionDetection object by introducing wrapper methods to unpack commonly used position objects like GridPosition and GridArea.

## Tasks

- [x] Add wrapper method for canPlaceBuilding for GridArea
- [x] Add wrapper method for placeBuilding for GridArea
- [x] Add wrapper method for removeBuilding for GridArea
